# Generated by Django 2.1.7 on 2019-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart_Waitlist',
            fields=[
                ('hos_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=75)),
                ('priority', models.CharField(choices=[('1a', '1a'), ('1b', '1b'), ('2', '2')], default='2', max_length=2)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], default='A', max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
            ],
        ),
    ]
